#############################################################################
# Makefile for building: ../../bin/xPLSimulator
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Aug 26 16:46:27 2013
# Project:  xPL_Simulator.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile xPL_Simulator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4 -I../lib -I../../build/xPLSimulator/moc -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtXmlPatterns -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../../build/xPLSimulator/obj/

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		xPLMessage.cpp \
		xPLNameValuePair.cpp \
		MessageListWidget.cpp \
		MessageWidget.cpp \
		utils.cpp \
		FilterDialog.cpp \
		MessageCreationDialog.cpp \
		xPL_NameValuePairForm.cpp \
		SendMessageDialog.cpp ../../build/xPLSimulator/moc/moc_MainWindow.cpp \
		../../build/xPLSimulator/moc/moc_MessageListWidget.cpp \
		../../build/xPLSimulator/moc/moc_MessageWidget.cpp \
		../../build/xPLSimulator/moc/moc_FilterDialog.cpp \
		../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp \
		../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp \
		../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp
OBJECTS       = ../../build/xPLSimulator/obj/main.o \
		../../build/xPLSimulator/obj/MainWindow.o \
		../../build/xPLSimulator/obj/xPLMessage.o \
		../../build/xPLSimulator/obj/xPLNameValuePair.o \
		../../build/xPLSimulator/obj/MessageListWidget.o \
		../../build/xPLSimulator/obj/MessageWidget.o \
		../../build/xPLSimulator/obj/utils.o \
		../../build/xPLSimulator/obj/FilterDialog.o \
		../../build/xPLSimulator/obj/MessageCreationDialog.o \
		../../build/xPLSimulator/obj/xPL_NameValuePairForm.o \
		../../build/xPLSimulator/obj/SendMessageDialog.o \
		../../build/xPLSimulator/obj/moc_MainWindow.o \
		../../build/xPLSimulator/obj/moc_MessageListWidget.o \
		../../build/xPLSimulator/obj/moc_MessageWidget.o \
		../../build/xPLSimulator/obj/moc_FilterDialog.o \
		../../build/xPLSimulator/obj/moc_MessageCreationDialog.o \
		../../build/xPLSimulator/obj/moc_xPL_NameValuePairForm.o \
		../../build/xPLSimulator/obj/moc_SendMessageDialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		xPL_Simulator.pro
QMAKE_TARGET  = xPLSimulator
DESTDIR       = ../../bin/
TARGET        = ../../bin/xPLSimulator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainWindow.h ui_MessageCreationDialog.h ui_xPL_NameValuePairForm.h ui_SendMessageDialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../../bin/ || $(MKDIR) ../../bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: xPL_Simulator.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile xPL_Simulator.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile xPL_Simulator.pro

dist: 
	@$(CHK_DIR_EXISTS) ../../build/xPLSimulator/obj/xPLSimulator1.0.0 || $(MKDIR) ../../build/xPLSimulator/obj/xPLSimulator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../../build/xPLSimulator/obj/xPLSimulator1.0.0/ && $(COPY_FILE) --parents MainWindow.h xPLMessage.h xPLNameValuePair.h MessageListWidget.h MessageWidget.h utils.h FilterDialog.h MessageCreationDialog.h xPL_NameValuePairForm.h SendMessageDialog.h ../../build/xPLSimulator/obj/xPLSimulator1.0.0/ && $(COPY_FILE) --parents main.cpp MainWindow.cpp xPLMessage.cpp xPLNameValuePair.cpp MessageListWidget.cpp MessageWidget.cpp utils.cpp FilterDialog.cpp MessageCreationDialog.cpp xPL_NameValuePairForm.cpp SendMessageDialog.cpp ../../build/xPLSimulator/obj/xPLSimulator1.0.0/ && $(COPY_FILE) --parents MainWindow.ui MessageCreationDialog.ui xPL_NameValuePairForm.ui SendMessageDialog.ui ../../build/xPLSimulator/obj/xPLSimulator1.0.0/ && (cd `dirname ../../build/xPLSimulator/obj/xPLSimulator1.0.0` && $(TAR) xPLSimulator1.0.0.tar xPLSimulator1.0.0 && $(COMPRESS) xPLSimulator1.0.0.tar) && $(MOVE) `dirname ../../build/xPLSimulator/obj/xPLSimulator1.0.0`/xPLSimulator1.0.0.tar.gz . && $(DEL_FILE) -r ../../build/xPLSimulator/obj/xPLSimulator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: ../../build/xPLSimulator/moc/moc_MainWindow.cpp ../../build/xPLSimulator/moc/moc_MessageListWidget.cpp ../../build/xPLSimulator/moc/moc_MessageWidget.cpp ../../build/xPLSimulator/moc/moc_FilterDialog.cpp ../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp ../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp ../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../../build/xPLSimulator/moc/moc_MainWindow.cpp ../../build/xPLSimulator/moc/moc_MessageListWidget.cpp ../../build/xPLSimulator/moc/moc_MessageWidget.cpp ../../build/xPLSimulator/moc/moc_FilterDialog.cpp ../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp ../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp ../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp
../../build/xPLSimulator/moc/moc_MainWindow.cpp: MessageListWidget.h \
		MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h \
		FilterDialog.h \
		SendMessageDialog.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o ../../build/xPLSimulator/moc/moc_MainWindow.cpp

../../build/xPLSimulator/moc/moc_MessageListWidget.cpp: MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h \
		MessageListWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MessageListWidget.h -o ../../build/xPLSimulator/moc/moc_MessageListWidget.cpp

../../build/xPLSimulator/moc/moc_MessageWidget.cpp: xPLMessage.h \
		xPLNameValuePair.h \
		MessageWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MessageWidget.h -o ../../build/xPLSimulator/moc/moc_MessageWidget.cpp

../../build/xPLSimulator/moc/moc_FilterDialog.cpp: FilterDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FilterDialog.h -o ../../build/xPLSimulator/moc/moc_FilterDialog.cpp

../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp: xPL_NameValuePairForm.h \
		xPLNameValuePair.h \
		MessageCreationDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MessageCreationDialog.h -o ../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp

../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp: xPLNameValuePair.h \
		xPL_NameValuePairForm.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) xPL_NameValuePairForm.h -o ../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp

../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp: xPLMessage.h \
		xPLNameValuePair.h \
		SendMessageDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SendMessageDialog.h -o ../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_MessageCreationDialog.h ui_xPL_NameValuePairForm.h ui_SendMessageDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_MessageCreationDialog.h ui_xPL_NameValuePairForm.h ui_SendMessageDialog.h
ui_MainWindow.h: MainWindow.ui
	/usr/bin/uic-qt4 MainWindow.ui -o ui_MainWindow.h

ui_MessageCreationDialog.h: MessageCreationDialog.ui
	/usr/bin/uic-qt4 MessageCreationDialog.ui -o ui_MessageCreationDialog.h

ui_xPL_NameValuePairForm.h: xPL_NameValuePairForm.ui
	/usr/bin/uic-qt4 xPL_NameValuePairForm.ui -o ui_xPL_NameValuePairForm.h

ui_SendMessageDialog.h: SendMessageDialog.ui
	/usr/bin/uic-qt4 SendMessageDialog.ui -o ui_SendMessageDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

../../build/xPLSimulator/obj/main.o: main.cpp MainWindow.h \
		MessageListWidget.h \
		MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h \
		FilterDialog.h \
		SendMessageDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/main.o main.cpp

../../build/xPLSimulator/obj/MainWindow.o: MainWindow.cpp MainWindow.h \
		MessageListWidget.h \
		MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h \
		FilterDialog.h \
		SendMessageDialog.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/MainWindow.o MainWindow.cpp

../../build/xPLSimulator/obj/xPLMessage.o: xPLMessage.cpp xPLMessage.h \
		xPLNameValuePair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/xPLMessage.o xPLMessage.cpp

../../build/xPLSimulator/obj/xPLNameValuePair.o: xPLNameValuePair.cpp xPLNameValuePair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/xPLNameValuePair.o xPLNameValuePair.cpp

../../build/xPLSimulator/obj/MessageListWidget.o: MessageListWidget.cpp MessageListWidget.h \
		MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/MessageListWidget.o MessageListWidget.cpp

../../build/xPLSimulator/obj/MessageWidget.o: MessageWidget.cpp MessageWidget.h \
		xPLMessage.h \
		xPLNameValuePair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/MessageWidget.o MessageWidget.cpp

../../build/xPLSimulator/obj/utils.o: utils.cpp utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/utils.o utils.cpp

../../build/xPLSimulator/obj/FilterDialog.o: FilterDialog.cpp FilterDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/FilterDialog.o FilterDialog.cpp

../../build/xPLSimulator/obj/MessageCreationDialog.o: MessageCreationDialog.cpp MessageCreationDialog.h \
		xPL_NameValuePairForm.h \
		xPLNameValuePair.h \
		ui_MessageCreationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/MessageCreationDialog.o MessageCreationDialog.cpp

../../build/xPLSimulator/obj/xPL_NameValuePairForm.o: xPL_NameValuePairForm.cpp xPL_NameValuePairForm.h \
		xPLNameValuePair.h \
		ui_xPL_NameValuePairForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/xPL_NameValuePairForm.o xPL_NameValuePairForm.cpp

../../build/xPLSimulator/obj/SendMessageDialog.o: SendMessageDialog.cpp SendMessageDialog.h \
		xPLMessage.h \
		xPLNameValuePair.h \
		ui_SendMessageDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/SendMessageDialog.o SendMessageDialog.cpp

../../build/xPLSimulator/obj/moc_MainWindow.o: ../../build/xPLSimulator/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_MainWindow.o ../../build/xPLSimulator/moc/moc_MainWindow.cpp

../../build/xPLSimulator/obj/moc_MessageListWidget.o: ../../build/xPLSimulator/moc/moc_MessageListWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_MessageListWidget.o ../../build/xPLSimulator/moc/moc_MessageListWidget.cpp

../../build/xPLSimulator/obj/moc_MessageWidget.o: ../../build/xPLSimulator/moc/moc_MessageWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_MessageWidget.o ../../build/xPLSimulator/moc/moc_MessageWidget.cpp

../../build/xPLSimulator/obj/moc_FilterDialog.o: ../../build/xPLSimulator/moc/moc_FilterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_FilterDialog.o ../../build/xPLSimulator/moc/moc_FilterDialog.cpp

../../build/xPLSimulator/obj/moc_MessageCreationDialog.o: ../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_MessageCreationDialog.o ../../build/xPLSimulator/moc/moc_MessageCreationDialog.cpp

../../build/xPLSimulator/obj/moc_xPL_NameValuePairForm.o: ../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_xPL_NameValuePairForm.o ../../build/xPLSimulator/moc/moc_xPL_NameValuePairForm.cpp

../../build/xPLSimulator/obj/moc_SendMessageDialog.o: ../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../build/xPLSimulator/obj/moc_SendMessageDialog.o ../../build/xPLSimulator/moc/moc_SendMessageDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

